spring:
  application:
    name: vtech

  datasource:
    url: jdbc:mysql://localhost:3306/vtech_db
    username: root
    password: mysqlDangDong2004@
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
#    drop-first: true

jwt:
  expiration: 86400000  # 24 giờ
  secretKey: ${JWT_SIGNER_KEY} # tối thiểu 256-bit / 32 ký tự

aws:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

gemini:
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
  api-key: ${GEMINI_API_KEY}

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:5173/payment/vnpay-return
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

cleanup-data:
#  expire-minutes: 1
#  cleanup-rate-ms: 5000
  expire-minutes: 43200
  cleanup-rate-ms: 3600000

app:
  review:
    sensitive-words: lừa đảo,chó,mẹ,địt,đm,vl,cc,vãi,cứt,cặc,lồn
  vpoint:
    exchange-rate: 10000 # 10.000đ = 1 điểm
    reward:
      review-text: 10    # Đánh giá chữ = 10 điểm
      review-media: 50   # Đánh giá hình ảnh = 50 điểm
      birthday: 500      # Quà sinh nhật = 500 điểm
    tier:
      silver: 1000       # Mốc Bạc (tương đương 10 triệu)
      gold: 5000         # Mốc Vàng (tương đương 50 triệu)
      diamond: 20000     # Mốc Kim Cương (tương đương 200 triệu)
    multiplier:
      member: 1.0        # Hạng thường: x1
      silver: 1.1        # Hạng Bạc: x1.1
      gold: 1.25         # Hạng Vàng: x1.25
      diamond: 1.5       # Hạng Kim Cương: x1.5

#security:
#  public:
#    post-endpoints:
#      - /api/v1/users/register
#      - /api/v1/login
#      - /api/v1/introspect
#      - /api/v1/logout
#      - /api/v1/refresh
#    get-endpoints:
#      - /api/v1/categories/**
#      - /api/v1/brands/**


